"""Side-by-side comparison of persisted no-SSL and Shadowseed answers."""

from __future__ import annotations

import hashlib
from typing import Any

from shadowseed.application.sessions import SessionService


class ComparisonService:
    """Compare outputs already produced by one chat turn.

    New live turns may contain either a same-history no-SSL control or an
    explicitly requested longitudinal vanilla control. Historical evaluation
    turns contain the isolated baseline generated by the evaluation runtime.
    The service never generates answers itself and never scores quality automatically.
    """

    def __init__(self, sessions: SessionService) -> None:
        self.sessions = sessions

    def compare_turn(
        self,
        session_id: str,
        turn_index: int,
        *,
        blinded: bool = True,
        reveal: bool = False,
    ) -> dict[str, Any]:
        stored = self.sessions.load(session_id)
        state = dict(stored["state"])
        reports = list(state.get("turn_reports", []))
        report = next(
            (
                item
                for index, item in enumerate(reports)
                if int(item.get("turn", index)) == int(turn_index)
            ),
            None,
        )
        if report is None:
            raise ValueError(f"turn {turn_index} does not exist in session {session_id}")
        state_config = dict(state.get("session_config", {}))
        persisted_config = dict(stored.get("config", {}))
        runtime_mode = (
            report.get("runtime_mode")
            or state_config.get("runtime_mode")
            or persisted_config.get("runtime_mode", "evaluation")
        )
        if runtime_mode not in {"evaluation", "live"}:
            runtime_mode = "evaluation"

        if runtime_mode == "live":
            control_value = report.get("comparison_control_answer")
            if control_value is None:
                raise ValueError(
                    "this live turn has no stored no-SSL control; request comparison when "
                    "sending the turn"
                )
            control = str(control_value)
            ssl_answer = str(report.get("comparison_ssl_answer", report.get("answer", "")))
            comparison_mode = str(report.get("comparison_mode", "authorized"))
            comparison_kind = str(report.get("comparison_kind", ""))
            source_labels = {
                "control": (
                    "vanilla"
                    if comparison_kind == "independent_vanilla_vs_ssl_path"
                    else "ssl_off"
                ),
                "ssl": (
                    "shadow_pressure"
                    if comparison_mode == "shadow_pressure"
                    else "ssl_on"
                ),
            }
        else:
            baseline_value = report.get("baseline_answer")
            if baseline_value is None:
                raise ValueError("evaluation turn does not contain a baseline answer")
            control = str(baseline_value)
            ssl_answer = str(report.get("ssl_answer", report.get("answer", "")))
            source_labels = {"control": "baseline", "ssl": "shadowseed"}

        # Stable ordering makes a blinded comparison reproducible without
        # persisting additional hidden state.
        digest = hashlib.sha256(f"{session_id}:{turn_index}".encode("utf-8")).digest()
        control_first = digest[0] % 2 == 0
        if control_first:
            candidate_a, candidate_b = control, ssl_answer
            mapping = {"A": source_labels["control"], "B": source_labels["ssl"]}
        else:
            candidate_a, candidate_b = ssl_answer, control
            mapping = {"A": source_labels["ssl"], "B": source_labels["control"]}
        result: dict[str, Any] = {
            "session_id": session_id,
            "turn": int(turn_index),
            "question": str(report.get("question", "")),
            "candidate_a": candidate_a,
            "candidate_b": candidate_b,
            "same_output": control == ssl_answer,
            "surfaced_seed_ids": list(
                report.get("comparison_seed_ids", report.get("surfaced_seed_ids", []))
            ),
            "comparison_mode": str(report.get("comparison_mode", "authorized")),
            "shadow_pressure_candidates": list(
                report.get("comparison_shadow_pressure_candidates", [])
            ),
            "ssl_influence_observed": bool(
                report.get(
                    "comparison_ssl_influence_observed",
                    report.get("comparison_seed_ids", report.get("surfaced_seed_ids", [])),
                )
            ),
            "current_ssl_influence_observed": bool(
                report.get(
                    "comparison_current_ssl_influence_observed",
                    report.get("comparison_seed_ids", report.get("surfaced_seed_ids", [])),
                )
            ),
            "prior_ssl_influence_observed": bool(
                report.get("comparison_prior_ssl_influence_observed", False)
            ),
            "prior_ssl_seed_ids": list(
                report.get("comparison_prior_ssl_seed_ids", [])
            ),
            "control_history_isolated": bool(
                report.get("comparison_control_history_isolated", False)
            ),
            "control_state_isolated": bool(
                report.get("comparison_control_state_isolated", False)
            ),
            "control_transport": report.get("comparison_control_transport"),
            "control_replayed_turns": int(
                report.get("comparison_control_replayed_turns", 0)
            ),
            "control_history_turns_before": int(
                report.get("comparison_control_history_turns_before", 0)
            ),
            "runtime_mode": runtime_mode,
            "comparison_kind": (
                report.get("comparison_kind")
                if runtime_mode == "live"
                else "legacy_evaluation_control"
            ),
            "blinded": bool(blinded),
            "interpretation": str(
                report.get(
                    "comparison_interpretation",
                    (
                        "The comparison record predates explicit vanilla-control provenance. "
                        "Interpret differences using the stored runtime and surfaced-seed metadata."
                    ),
                )
            ),
        }
        if not blinded:
            result["candidate_a_label"] = mapping["A"]
            result["candidate_b_label"] = mapping["B"]
        elif reveal:
            result["revealed_mapping"] = mapping
        return result
